### ISSUE TITLE
정렬 알고리즘 풀이

### ISSUE THREAD

**Issue by hyunjungkimm** [hyunjungkimm/Algorithm#4]
정렬 알고리즘 풀이 후 리뷰하는 것을 목표로 한다.

[일정]
4/29 스터디 :  10825, 1015, 11652 (+ 완전탐색 2문제 풀이) 
5/4 스터디 : 15970, 1181, 20291

[개념 정리]
담당 : 김서영

**Comment by seoyyyy** [comment]
## 개념

- 순서 없이 나열된 데이터 리스트를 번호순이나 사전순서와 같이 특정한 기준의 순서대로 열거하는 알고리즘
- 정렬 알고리즘은 알고리즘의 효율성을 쉽게 이해할 수 있는 다양한 알고리즘의 핵심이 되는 개념이다.

## 분류 방법

- **비교정렬(Comparison Sort)**
    - 원소들을 정렬할 때 원소들의 순서에만 의존하는 알고리즘들
    - 아무리 빠른 알고리즘이어도 최악의 경우 O(n log n) 시간을 필요로 한다.
    - **종류)** **선택 정렬, 버블 정렬, 삽입 정렬, 퀵 정렬, 힙 정렬, 병합 정렬 등**
    - 비 비교정렬 - 버킷정렬, 계수 정렬, 기수 정렬
- **제자리정렬(In-place Sort)**
    - 입력 배열(정렬되지 않은 값들) 이외에 다른 추가 메모리를 요구하지 않는 정렬 방법
    - 원소를 넣을 위치(순서)는 정해져 있고, 어떤 원소를 넣을지를 선택하는 알고리즘
    - **종류)** **삽입정렬, 선택정렬, 버블정렬, 퀵정렬, 힙정렬**
- **안정정렬(Stable sort)**
    - 동일한 값에 대해 기존의 순서가 유지되는 정렬 방식
    - **종류) 버블정렬, 삽입정렬**
- **불안정 정렬(Not stable sort)**
    - ㅇ동일한 값에 대해 기존의 순서가 뒤바뀔 수 있는 정렬 방식
    - **종류) 선택정렬, 퀵정렬**
    
    ![https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Sorting_stability_playing_cards.svg/220px-Sorting_stability_playing_cards.svg.png](https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Sorting_stability_playing_cards.svg/220px-Sorting_stability_playing_cards.svg.png)
    

- **내부정렬(Internal sort)**
    - 메모리에 모든 데이터를 올려 정렬하는 방법
    - 데이터량이 적을 때는 속도가 빠르며 적합하지만 데이터의 양이 많을 경우 부적합하다.
    - **종류) 삽입정렬, 선택정렬, 쉘정렬, 버블정렬, 퀵정렬, 힙정렬, 기수정렬, 병합정렬**
- **외부정렬(External sort)**
    - 대용량의 데이터를 몇 개의 서브 파일로 나누어 각각 내부 정렬을 한 후에 테이프나 디스크 내에서 각 서브파일을 합병하는 방법
    - 속도는 내부정렬보다 느리지만 대용량 자료를 정렬할 수 있다.
    - **종류) 진동 병합 정렬, 캐스케이드 병합정렬, 폴리파즈 병합정렬, 균형 병합정렬**

## 종류

- **코테 문제 & 기술면접 질문**에서 자주 사용되어지는 정렬 알고리즘의 종류
- **거품정렬(Bubble Sort)**
    - 두개의 인접한 원소를 비교, 정렬하려는 조건에 맞지 않다면 서로 자리를 교환하며 정렬하는 알고리즘
    - **제자리 정렬 알고리즘(In-place Sort)**으로 정렬하고자 하는 배열안에서 교환하는 방식, 추가적인 메모리 공간을 필요로 하지않음
    - **안정 정렬(Stable Sort)**
    - 정렬되어있지 않은 원소를 정렬하기 위해 **교환연산(swap)**이 많이 일어나게 됨
    - 시간복잡도: ****최선, 평균,최악의 경우 모두 **O(n^2)**  ⇒ **비효율적**
    - 공간복잡도: **O(n)**
    
    ![https://github.com/GimunLee/tech-refrigerator/blob/master/Algorithm/resources/bubble-sort-001.gif?raw=true](https://github.com/GimunLee/tech-refrigerator/blob/master/Algorithm/resources/bubble-sort-001.gif?raw=true)
    
- **선택정렬(Selection Sort)**
    - 해당 순서에 원소를 넣을 위치는 이미 정해져 있으며 어떤 원소를 넣을지 선택하는 알고리즘
    - 주어진 배열중 최소값을 찾고, 그 값을 맨앞에 위치한 값과 교체, 맨 처음 위치를 뺀 나머지 배열을 같은 방법으로 교체
    - 거품정렬(Bubble Sort)와 유사한 알고리즘(**제자리 정렬 알고리즘 - In-place Sort)**
    - **불안정 정렬(Unstable Sort)**
    - 시간복잡도: 최선, 평균, 최악의 경우 모두 **O(n^2) ⇒ 비효율적**
    - 공간복잡도: **O(n)**
    
    ![https://github.com/GimunLee/tech-refrigerator/blob/master/Algorithm/resources/selection-sort-001.gif?raw=true](https://github.com/GimunLee/tech-refrigerator/blob/master/Algorithm/resources/selection-sort-001.gif?raw=true)
    
- **삽입정렬(Insertion Sort)**
    - 2번째 원소부터 시작하며 앞의 이미 정렬이 완료된 원소들과 비교, 삽입 위치를 지정한 후 원소들을 뒤로 옮기고 지정한 자리에 자료를 삽입하여 정렬
    - 원소가 이미 정렬되어있는 경우 매우 효율적
    - **제자리 정렬 알고리즘(In-place Sort)**
    - **안정정렬(Stable Sort)**
    - 선택정렬, 거품정렬에 비해 상대적으로 빠름
    - 배열이 길이가 길어질수록 비효율적(선택정렬, 거품정렬도 해당)
    - 시간복잡도: 최선(이미 정렬된 경우)의 경우 **O(n),** 평균과 최악(역으로 정렬된 경우)의 경우 **O(n^2)**
    - 공간복잡도: **O(n)**
    
    ![https://github.com/GimunLee/tech-refrigerator/blob/master/Algorithm/resources/insertion-sort-001.gif?raw=true](https://github.com/GimunLee/tech-refrigerator/blob/master/Algorithm/resources/insertion-sort-001.gif?raw=true)
    
- **퀵정렬(Quick Sort)**
    - 배열 가운데 하나의 원소를 골라 **피벗(pivot)**으로 지정
    - 피벗 앞에는 피벗보다 값이 작은 원소들을 이동, 피벗 뒤에는 피벗보다 값이 큰 원소들을 이동시키며 피벗 기준으로 배열을 둘로 나눈다 - **분할(Divide).**
    - 두개로 분할된 배열에서 다시 재귀적으로 이 과정을 반복한다.
    - 평균적으로는 가장 빠른 알고리즘
    - **불안정정렬(Unstable Sort)**
    - **비교정렬**
    - 분할 정복 알고리즘(Divide and Conquer)
    - 비균등 분할(반대: 병합정렬(Merge Sort))
    - 시간복잡도: 평균, 최선의 경우 ****O(nlog₂n)****, 피벗값이 최소값이거나 최대값일 때, 즉 배열이 이미 오름차순이나 내림차순으로 정렬되어있으면 최악의 경우 **O(n^2)**
    - 공간복잡도: **O(n)**
    
    ![https://github.com/GimunLee/tech-refrigerator/blob/master/Algorithm/resources/quick-sort-001.gif?raw=true](https://github.com/GimunLee/tech-refrigerator/blob/master/Algorithm/resources/quick-sort-001.gif?raw=true)
    
- **병합정렬(Merge Sort)**
    - 요소를 쪼갠 후 다시 합병시키면서 정렬해나가는 방식으로 퀵정렬과 유사
    - 분할 정복(Divide and Conquer) 알고리즘
    - **분할(Divide) → 정복(Conquer) → 결합(Combine)** 의 단계로 이루어진다.
    - 퀵정렬과 차이점
        - **퀵정렬:** 1. 피벗을 통해 정렬 → 2. 영역을 쪼갬
        - **병합정렬:** 영역을 쪼갤 수 있을만큼 쪼갬 → 합병시키며 정렬
    - **안정정렬(Stable Sort)**
    - **제자리 정렬(in-place sort)이 아니다.**
    - 이미 합병의 대상이 되는 두 영역이 각 영역에 대해서 정렬되어있는 상태이기 때문에 단순히 두 배열을 순차적으로 비교하며 정렬할 수 있음
    - **LinkedList**의 정렬이 필요할 때 사용 시 효율적(퀵정렬에서 사용 시 비효율적)
    - 시간복잡도: 평균, 최선, 최악 모두 ****O(nlog₂n)****
    - 공간복잡도: **O(n)**
- **계수정렬(Counting Sort)**
    - 모든 숫자의 개수를 세어, 누적 합을 구하고 누적합의 인덱스를 활용하여 숫자를 다시 넣어주는 방식
    - **비교기반의 정렬 알고리즘이 아님**
    - 데이터의 크기 범위가 제한되어 정수 형태로 표현할 수 있을 때만 사용할 수 있다.
    - 일반적으로 가장 큰 데이터와 가장 작은 데이터의 차이가 1,000,000을 넘지 않을 때 효과적으로 사용할 수 있다.
    - 시간복잡도: **O(n + k )** // k는 배열에서 등장하는 최대값
    - 공간복잡도: **O(k)** // 비교해야하는 숫자의범위가 크면 그만큼 메모리 낭비가 심함
    
- 그 밖에 정렬 알고리즘: 힙정렬, 기수정렬 등
