### ISSUE TITLE
이분 탐색 알고리즘 풀이

### ISSUE THREAD

**Issue by hyunjungkimm** [hyunjungkimm/Algorithm#8]
이분 탐색 알고리즘 풀이 후 리뷰하는 것을 목표로 한다.

[일정]
5/11 : 7795, 2470, 2805, 2110, 1920, 1764

[개념 정리]
담당 : 조화진

**Comment by hwajin-jo** [comment]
### 이분 탐색(Binary Search)

-  이진 탐색 혹은 이분 탐색이라고 부른다.

- 이미 정렬되어 있는 자료 구조에서 특정 값을 찾을 때, 탐색 범위를 절반씩 나눠가면서 해당 값을 찾아가는 것이다.
즉, 탐색 범위를 두 부분으로 분할하면서 찾는 방식이다.

- 처음부터 끝까지 돌면서 탐색하는 것보다 훨씬 빠르다는 장점을 가지고 있다.

- 시간 복잡도
순차 탐색 : O(N)
이분 탐색 : O(logN)

### 문제 예시
![68747470733a2f2f7777772e66756e2d636f64696e672e6f72672f30305f496d616765732f62696e6172797365617263682e706e67](https://user-images.githubusercontent.com/70902597/167363514-96babd75-da70-43c1-8d43-f27950675f32.png)


### 이진 탐색의 이해 (이진탐색과 순차탐색)
![68747470733a2f2f7777772e6d61746877617265686f7573652e636f6d2f70726f6772616d6d696e672f696d616765732f62696e6172792d76732d6c696e6561722d7365617263682f62696e6172792d616e642d6c696e6561722d7365617263682d616e696d6174696f6e732e676966](https://user-images.githubusercontent.com/70902597/167360862-b8e77516-216f-4ae6-8508-a86cf550651d.gif)

- 진행 순서
1. 정렬을 한다.
2. left와 right로 mid 값을 설정한다.
3. mid와 구하고자 하는 값을 비교한다.
4. 구할 값이 mid보다 크면 -> left = mid + 1
5. 구할 값이 mid보다 낮으면 -> right = mid - 1
6. right < left가 될 때까지 계속 반복한다.
